### ISSUE TITLE
Bop for f-droid

### ISSUE THREAD

**Issue by theScrabi** [iamSahdeep/Bop#12]
Have you thought about bringing your app to the [fdroid](https://f-droid.org/) repository? I could help you with that if you have questions. :)

**Comment by iamSahdeep** [comment]
Hi @theScrabi , I have looked the procedure but found it bit confusing. It would be great if you guide me on it. Thank you.

**Comment by theScrabi** [comment]
Ok so if you use python, and a unix machine like mac or linux, you can try to install fdroid using "sudo pip install fdroidserver"

Also you would want to pull the git representation of the fdroid repositorry. You can get it from here:
https://gitlab.com/fdroid/fdroiddata

Take a look into the metadata folder:
https://gitlab.com/fdroid/fdroiddata/blob/master/metadata

They have the fdroid build files.

Try writing one like this for Bop:
https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/at.bitfire.icsdroid.txt

Use the documentation for help:
https://f-droid.org/de/docs/Build_Metadata_Reference/

Once done move to the root folder of fdroiddata and run "fdroid lint -f". If there are no errors good if not pleas post ur file here, ill complete it.

However im short on time rn, so it would take some while.

**Comment by iamSahdeep** [comment]
Hey, I tried your method and gone far with docs. Everything works great and i have created the metadata file too. But the problem i am facing is that I can't build App with fdroidserver i.e., with this `fdroid build`, even though application works perfectly if it is build on my machine or on travis.

Error was : `Minimum supported Gradle version is 4.6. Current version is 3.4.1.` buti have gradle version 4.6 in my project. Also before this issue there was this issue `Could not find method google() for arguments [] on repository container ` but i resolved it by expanding those methods,

Documentation i have followed was : https://gitlab.com/fdroid/fdroiddata/blob/master/CONTRIBUTING.md#merge-requests

Here is the generated metadeta file in yml format :
```
Categories:
  - Multimedia
License: Apache-2.0
SourceCode: https://github.com/iamSahdeep/Bop
IssueTracker: https://github.com/iamSahdeep/Bop/issues
Changelog: https://github.com/iamSahdeep/Bop/blob/HEAD/changelog.md
Donate: https://www.paypal.me/sahdeep

AutoName: Bop-MusicPlayer

RepoType: git
Repo: https://github.com/iamSahdeep/Bop

Builds:
  - versionName: '0.5'
    versionCode: 5
    commit: c5e1db6fde186cd6050971c876f048fa9be6a726
    subdir: app
    gradle:
      - yes

AutoUpdateMode: Version v%v
UpdateCheckMode: Tags
CurrentVersion: '0.5'
CurrentVersionCode: 5 
```
